/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
Exception in thread Thread-1:
Exception in thread Traceback (most recent call last):
Thread-1:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        self.run()self.run()

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
        pubsub.get_message(ignore_subscribe_messages=True,pubsub.get_message(ignore_subscribe_messages=True,

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
        response = self.parse_response(block=False, timeout=timeout)response = self.parse_response(block=False, timeout=timeout)

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    return self._parser.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
        if not block and not conn.can_read(timeout=timeout):if not block and not conn.can_read(timeout=timeout):

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
        return self._parser.can_read(timeout)return self._parser.can_read(timeout)

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
        return self._buffer and self._buffer.can_read(timeout)return self._buffer and self._buffer.can_read(timeout)

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
        self._read_from_socket(timeout=timeout,self._read_from_socket(timeout=timeout,

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
        raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)

redis.exceptionsredis.exceptions..ConnectionErrorConnectionError: : Connection closed by server.Connection closed by server.

/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/utils.py:281: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return StrictVersion('.'.join(version_string.split('.')[:3]))
/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py:308: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if self.get_redis_server_version() >= StrictVersion("4.0.0"):
Traceback (most recent call last):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 706, in send_packed_command
Traceback (most recent call last):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    sendall(self._sock, item)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/_compat.py", line 9, in sendall
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
      File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return sock.sendall(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)exec(code, run_globals)

  File "/home/karthik/project_bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    main()
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    click.Group(commands=commands)(prog_name="bench")
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    return self.main(*args, **kwargs)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    rv = self.invoke(ctx)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/karthik/project_bench/apps/frappe/frappe/commands/scheduler.py", line 204, in start_worker
Traceback (most recent call last):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    return callback(*args, **kwargs)
  File "/home/karthik/project_bench/apps/frappe/frappe/commands/scheduler.py", line 204, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/background_jobs.py", line 202, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/background_jobs.py", line 202, in start_worker
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    sock = self._connect()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
        self.register_death()self.register_death()

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    raise err
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
        p.execute()p.execute()

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
        return execute(conn, stack, raise_on_error)return execute(conn, stack, raise_on_error)

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3886, in _execute_transaction
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)    
self.parse_response(connection, '_')  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    connection.send_packed_command(all_cmds)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 717, in send_packed_command
    return callback(*args, **kwargs)
  File "/home/karthik/project_bench/apps/frappe/frappe/commands/scheduler.py", line 204, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/karthik/project_bench/apps/frappe/frappe/utils/background_jobs.py", line 202, in start_worker
    raise ConnectionError("Error %s while writing to socket. %s." %
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    result = Redis.parse_response(
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    conn = self.connection_pool.get_connection('MULTI',Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = connection.read_response()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
        response = self.parse_response(block=False, timeout=timeout)response = self._parser.read_response()

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    if not block and not conn.can_read(timeout=timeout):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    self.run()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    if not block and not conn.can_read(timeout=timeout):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
        return self._parser.can_read(timeout)return self._buffer and self._buffer.can_read(timeout)

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError    : self._read_from_socket(timeout=timeout,Connection closed by server.

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    connection.connect()
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/karthik/project_bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
